-- RevenueLens :: RBAC
-- Functional role hierarchy, owned by SYSADMIN. All privileges are granted to
-- ROLES; users only ever receive ROLE grants (GRANT ROLE ... TO USER), never
-- direct object grants -- this keeps access auditable via SHOW GRANTS TO ROLE
-- and means D4 ("governance in 90 seconds") is a login-and-look demo, not a
-- pile of one-off exceptions.
--
-- Hierarchy:
--   SYSADMIN
--     -> RL_ADMIN                  (owns every RL_* object)
--          -> RL_LOADER             ingestion (Airflow / Snowpipe / Streams-Tasks)
--          -> RL_TRANSFORMER        dbt run/test/snapshot
--          -> RL_REVENUE_CONTROLLER full, unmasked, all-entity read on marts
--          -> RL_FINANCE_ANALYST    masked + entity-restricted read on marts
--          -> RL_BI_READER          read-only, masked, for Snowsight dashboards
--
-- Idempotent: safe to re-run.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS RL_ADMIN
    COMMENT = 'RevenueLens - owns all RL_* objects, parent of every functional role';
CREATE ROLE IF NOT EXISTS RL_LOADER
    COMMENT = 'RevenueLens - ingestion: writes RAW, runs Snowpipe/Streams/Tasks';
CREATE ROLE IF NOT EXISTS RL_TRANSFORMER
    COMMENT = 'RevenueLens - dbt: reads RAW, writes STAGING/INTERMEDIATE/MARTS_FINANCE';
CREATE ROLE IF NOT EXISTS RL_REVENUE_CONTROLLER
    COMMENT = 'RevenueLens - full unmasked, all-entity read on finance marts';
CREATE ROLE IF NOT EXISTS RL_FINANCE_ANALYST
    COMMENT = 'RevenueLens - masked, entity-restricted read on finance marts';
CREATE ROLE IF NOT EXISTS RL_BI_READER
    COMMENT = 'RevenueLens - read-only masked access for Snowsight dashboards';

-- Hierarchy wiring: SYSADMIN sits above RL_ADMIN so admins retain full
-- visibility; every functional role rolls up into RL_ADMIN.
GRANT ROLE RL_ADMIN TO ROLE SYSADMIN;
GRANT ROLE RL_LOADER TO ROLE RL_ADMIN;
GRANT ROLE RL_TRANSFORMER TO ROLE RL_ADMIN;
GRANT ROLE RL_REVENUE_CONTROLLER TO ROLE RL_ADMIN;
GRANT ROLE RL_FINANCE_ANALYST TO ROLE RL_ADMIN;
GRANT ROLE RL_BI_READER TO ROLE RL_ADMIN;

USE ROLE SYSADMIN;

-- RL_ADMIN owns every database so it can create/alter schemas, policies, etc.
GRANT OWNERSHIP ON DATABASE RL_DEV  TO ROLE RL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE RL_QA   TO ROLE RL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE RL_PROD TO ROLE RL_ADMIN COPY CURRENT GRANTS;

USE ROLE RL_ADMIN;

-- ---------------------------------------------------------------------------
-- RL_LOADER: ingestion only ever touches RAW, in every environment.
-- ---------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE RL_LOADING_WH TO ROLE RL_LOADER;

GRANT USAGE ON DATABASE RL_DEV TO ROLE RL_LOADER;
GRANT USAGE ON DATABASE RL_QA TO ROLE RL_LOADER;
GRANT USAGE ON DATABASE RL_PROD TO ROLE RL_LOADER;

GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA RL_DEV.RAW TO ROLE RL_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA RL_QA.RAW TO ROLE RL_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA RL_PROD.RAW TO ROLE RL_LOADER;

GRANT INSERT, SELECT, TRUNCATE ON FUTURE TABLES IN SCHEMA RL_DEV.RAW TO ROLE RL_LOADER;
GRANT INSERT, SELECT, TRUNCATE ON FUTURE TABLES IN SCHEMA RL_QA.RAW TO ROLE RL_LOADER;
GRANT INSERT, SELECT, TRUNCATE ON FUTURE TABLES IN SCHEMA RL_PROD.RAW TO ROLE RL_LOADER;

-- ---------------------------------------------------------------------------
-- RL_TRANSFORMER: dbt reads RAW, owns everything downstream of it.
-- ---------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE RL_TRANSFORMING_WH TO ROLE RL_TRANSFORMER;

-- Streamlit apps run with their OWNER's rights, not the viewer's --
-- RL_CFO_ARR_DASHBOARD (demo/deploy_dashboard.py) is owned by
-- RL_TRANSFORMER (it ran the CREATE STREAMLIT), so RL_TRANSFORMER needs
-- USAGE on the app's QUERY_WAREHOUSE even though RL_TRANSFORMER never
-- queries RL_BI_WH directly itself. Without this, every query in the app
-- fails with "No active warehouse selected" regardless of which role opens
-- it in Snowsight -- confirmed live; this was the actual root cause after
-- ruling out AUTO_SUSPEND timing, the row access policy on
-- FCT_ARR_WATERFALL_ACCOUNT_MONTHLY, and to_pandas() vs collect().
GRANT USAGE ON WAREHOUSE RL_BI_WH TO ROLE RL_TRANSFORMER;

-- CI (.github/workflows/dbt_ci.yml) runs as RL_TRANSFORMER too, on
-- RL_CI_WH, and creates/drops a zero-copy clone of RL_PROD per PR --
-- CREATE DATABASE is account-level in Snowflake (no narrower scope exists),
-- and granting an account-level privilege requires ACCOUNTADMIN
-- specifically -- RL_ADMIN (and even SECURITYADMIN) get "insufficient
-- privileges" on this one grant, confirmed live.
GRANT USAGE ON WAREHOUSE RL_CI_WH TO ROLE RL_TRANSFORMER;
USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE RL_TRANSFORMER;
USE ROLE RL_ADMIN;

GRANT USAGE ON DATABASE RL_DEV TO ROLE RL_TRANSFORMER;
GRANT USAGE ON DATABASE RL_QA TO ROLE RL_TRANSFORMER;
GRANT USAGE ON DATABASE RL_PROD TO ROLE RL_TRANSFORMER;

GRANT USAGE ON SCHEMA RL_DEV.RAW TO ROLE RL_TRANSFORMER;
GRANT USAGE ON SCHEMA RL_QA.RAW TO ROLE RL_TRANSFORMER;
GRANT USAGE ON SCHEMA RL_PROD.RAW TO ROLE RL_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RL_DEV.RAW TO ROLE RL_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RL_QA.RAW TO ROLE RL_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RL_PROD.RAW TO ROLE RL_TRANSFORMER;

-- dbt needs CREATE on STAGING/INTERMEDIATE/MARTS_FINANCE in every env, plus
-- ownership-equivalent DML rights so it can build/drop/replace models freely.
-- CREATE TABLE/CREATE VIEW are schema-level-only privileges in Snowflake
-- (granting them at the database level is a compile error) -- they're
-- covered per-schema by the GRANT ALL ON SCHEMA statements below instead.
GRANT USAGE, CREATE SCHEMA
    ON DATABASE RL_DEV TO ROLE RL_TRANSFORMER;
GRANT USAGE, CREATE SCHEMA
    ON DATABASE RL_QA TO ROLE RL_TRANSFORMER;
GRANT USAGE, CREATE SCHEMA
    ON DATABASE RL_PROD TO ROLE RL_TRANSFORMER;

GRANT ALL ON SCHEMA RL_DEV.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_DEV.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_DEV.MARTS_FINANCE TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_QA.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_QA.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_QA.MARTS_FINANCE TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_PROD.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_PROD.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_TRANSFORMER;

GRANT ALL ON FUTURE TABLES IN SCHEMA RL_DEV.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_DEV.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RL_DEV.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_DEV.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RL_DEV.MARTS_FINANCE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_DEV.MARTS_FINANCE TO ROLE RL_TRANSFORMER;

GRANT ALL ON FUTURE TABLES IN SCHEMA RL_QA.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_QA.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RL_QA.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_QA.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RL_QA.MARTS_FINANCE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_QA.MARTS_FINANCE TO ROLE RL_TRANSFORMER;

GRANT ALL ON FUTURE TABLES IN SCHEMA RL_PROD.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_PROD.STAGING TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RL_PROD.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_PROD.INTERMEDIATE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_TRANSFORMER;

-- D5 cost view (rpt_cost_by_layer_daily) reads SNOWFLAKE.ACCOUNT_USAGE,
-- which is invisible without this grant regardless of any other privilege
-- RL_TRANSFORMER holds -- ACCOUNT_USAGE is gated by IMPORTED PRIVILEGES on
-- the SNOWFLAKE database specifically, granted per-role, not inherited
-- through the RL_ADMIN hierarchy (confirmed live: granting it to RL_ADMIN
-- alone does not extend it to RL_TRANSFORMER, since RL_ADMIN inherits FROM
-- RL_TRANSFORMER, not the other way).
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE RL_TRANSFORMER;

-- RL_TRANSFORMER also needs the ability to create/apply masking & row access
-- policies (dbt post-hooks run as this role) and to manage snapshots' schema.
GRANT CREATE MASKING POLICY, CREATE ROW ACCESS POLICY
    ON SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_TRANSFORMER;
GRANT CREATE MASKING POLICY, CREATE ROW ACCESS POLICY
    ON SCHEMA RL_QA.MARTS_FINANCE TO ROLE RL_TRANSFORMER;
GRANT CREATE MASKING POLICY, CREATE ROW ACCESS POLICY
    ON SCHEMA RL_DEV.MARTS_FINANCE TO ROLE RL_TRANSFORMER;

-- ---------------------------------------------------------------------------
-- Consumption roles: read-only on PROD marts. Only RL_TRANSFORMER writes;
-- these three roles never get INSERT/UPDATE/CREATE anywhere.
-- ---------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE RL_BI_WH TO ROLE RL_REVENUE_CONTROLLER;
GRANT USAGE ON WAREHOUSE RL_BI_WH TO ROLE RL_FINANCE_ANALYST;
GRANT USAGE ON WAREHOUSE RL_BI_WH TO ROLE RL_BI_READER;

GRANT USAGE ON DATABASE RL_PROD TO ROLE RL_REVENUE_CONTROLLER;
GRANT USAGE ON DATABASE RL_PROD TO ROLE RL_FINANCE_ANALYST;
GRANT USAGE ON DATABASE RL_PROD TO ROLE RL_BI_READER;

GRANT USAGE ON SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_REVENUE_CONTROLLER;
GRANT USAGE ON SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_FINANCE_ANALYST;
GRANT USAGE ON SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_BI_READER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_REVENUE_CONTROLLER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_REVENUE_CONTROLLER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_FINANCE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_FINANCE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_BI_READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_BI_READER;

-- The D1 dashboard (demo/deploy_dashboard.py -> RL_CFO_ARR_DASHBOARD) is a
-- STREAMLIT object, a distinct grantable type from TABLE/VIEW -- the
-- FUTURE TABLES/VIEWS grants above don't cover it. Using FUTURE STREAMLITS
-- (not a specific-object grant) so this runs cleanly on a fresh environment
-- before the app has ever been deployed -- infra scripts run in order
-- 01-08, long before demo/deploy_dashboard.py ever executes.
GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_BI_READER;
GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA RL_PROD.MARTS_FINANCE TO ROLE RL_REVENUE_CONTROLLER;

-- Masking (04) and row access (05) policies differentiate RL_REVENUE_CONTROLLER
-- (unmasked, all-entity) from RL_FINANCE_ANALYST (masked, entity-scoped) even
-- though both hold identical SELECT grants above -- the policy, not the grant,
-- is what enforces D4.

-- ---------------------------------------------------------------------------
-- Example user assignment (uncomment and edit for real POC users).
-- Users NEVER receive object grants directly -- only role grants.
-- ---------------------------------------------------------------------------
-- CREATE USER IF NOT EXISTS demo_finance_analyst PASSWORD = '...' MUST_CHANGE_PASSWORD = TRUE DEFAULT_ROLE = RL_FINANCE_ANALYST;
-- GRANT ROLE RL_FINANCE_ANALYST TO USER demo_finance_analyst;
--
-- CREATE USER IF NOT EXISTS demo_revenue_controller PASSWORD = '...' MUST_CHANGE_PASSWORD = TRUE DEFAULT_ROLE = RL_REVENUE_CONTROLLER;
-- GRANT ROLE RL_REVENUE_CONTROLLER TO USER demo_revenue_controller;
--
-- CREATE USER IF NOT EXISTS svc_airflow_loader PASSWORD = '...' DEFAULT_ROLE = RL_LOADER;
-- GRANT ROLE RL_LOADER TO USER svc_airflow_loader;
--
-- CREATE USER IF NOT EXISTS svc_dbt_transformer PASSWORD = '...' DEFAULT_ROLE = RL_TRANSFORMER;
-- GRANT ROLE RL_TRANSFORMER TO USER svc_dbt_transformer;
